import numpy as np
a=np.arange(10).reshape(2,5)
print(a)

print(a+10)
print(a.shape)
print(a.size)
b=np.zeros((2,5))
c=np.ones((2,5))
print(b)
print(c)
print(a.reshape(2,5))
print(a.flatten())

print(np.hstack((a,b,c)))
print(np.vstack((a,b,c)))
#normal distribution
n=np.random.normal(5,10,10)
print(n)
d=np.matrix(b)
print(d)
print(np.arange(1,10,2))
print(np.linspace(3,4,num=4,endpoint=False))
print(np.linspace(3,4,4))
print(np.logspace(3,4,4))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
